apiVersion: 1

datasources:
  - name: Mimir
    uid: mimir-local
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    editable: true

  - name: Loki
    uid: loki-local
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
